name: "Get Cluster Info"
author: iStreamPlanet
description: "Gets info from clusters such as kubernetes and helm versions"
inputs:
  working_directory:
    description: "The base path for a repository"
    required: true
runs:
  using: "composite"
  steps:
    - name: install-deps
      shell: bash
      run: pip install --no-cache-dir -r ${{ github.action_path }}/requirements.txt
    
    - name: get-info
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: python ${{ github.action_path }}/src/main.py
